<?php
/**
 * ConversationUseViewResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Forsta Atlas API
 *
 * User and Tag management API for Forsta Messaging Platform
 *
 * OpenAPI spec version: v1
 * Contact: support@forsta.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ConversationUseViewResponse Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConversationUseViewResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ConversationUseViewResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'thread_id' => 'string',
        'distribution' => 'string',
        'creator_id' => 'string',
        'org_id' => 'string',
        'user_ids' => 'string[]',
        'expires' => 'string',
        'created' => 'string',
        'jwt' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'thread_id' => null,
        'distribution' => null,
        'creator_id' => null,
        'org_id' => null,
        'user_ids' => null,
        'expires' => null,
        'created' => null,
        'jwt' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'thread_id' => 'thread_id',
        'distribution' => 'distribution',
        'creator_id' => 'creator_id',
        'org_id' => 'org_id',
        'user_ids' => 'user_ids',
        'expires' => 'expires',
        'created' => 'created',
        'jwt' => 'jwt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'thread_id' => 'setThreadId',
        'distribution' => 'setDistribution',
        'creator_id' => 'setCreatorId',
        'org_id' => 'setOrgId',
        'user_ids' => 'setUserIds',
        'expires' => 'setExpires',
        'created' => 'setCreated',
        'jwt' => 'setJwt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'thread_id' => 'getThreadId',
        'distribution' => 'getDistribution',
        'creator_id' => 'getCreatorId',
        'org_id' => 'getOrgId',
        'user_ids' => 'getUserIds',
        'expires' => 'getExpires',
        'created' => 'getCreated',
        'jwt' => 'getJwt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['thread_id'] = isset($data['thread_id']) ? $data['thread_id'] : null;
        $this->container['distribution'] = isset($data['distribution']) ? $data['distribution'] : null;
        $this->container['creator_id'] = isset($data['creator_id']) ? $data['creator_id'] : null;
        $this->container['org_id'] = isset($data['org_id']) ? $data['org_id'] : null;
        $this->container['user_ids'] = isset($data['user_ids']) ? $data['user_ids'] : null;
        $this->container['expires'] = isset($data['expires']) ? $data['expires'] : null;
        $this->container['created'] = isset($data['created']) ? $data['created'] : null;
        $this->container['jwt'] = isset($data['jwt']) ? $data['jwt'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['thread_id'] === null) {
            $invalidProperties[] = "'thread_id' can't be null";
        }
        if ((mb_strlen($this->container['thread_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'thread_id', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['distribution'] === null) {
            $invalidProperties[] = "'distribution' can't be null";
        }
        if ((mb_strlen($this->container['distribution']) < 1)) {
            $invalidProperties[] = "invalid value for 'distribution', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['creator_id'] === null) {
            $invalidProperties[] = "'creator_id' can't be null";
        }
        if ((mb_strlen($this->container['creator_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'creator_id', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['org_id'] === null) {
            $invalidProperties[] = "'org_id' can't be null";
        }
        if ((mb_strlen($this->container['org_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'org_id', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['user_ids'] === null) {
            $invalidProperties[] = "'user_ids' can't be null";
        }
        if ($this->container['expires'] === null) {
            $invalidProperties[] = "'expires' can't be null";
        }
        if ((mb_strlen($this->container['expires']) < 1)) {
            $invalidProperties[] = "invalid value for 'expires', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['created'] === null) {
            $invalidProperties[] = "'created' can't be null";
        }
        if ((mb_strlen($this->container['created']) < 1)) {
            $invalidProperties[] = "invalid value for 'created', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['jwt'] === null) {
            $invalidProperties[] = "'jwt' can't be null";
        }
        if ((mb_strlen($this->container['jwt']) < 1)) {
            $invalidProperties[] = "invalid value for 'jwt', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets thread_id
     *
     * @return string
     */
    public function getThreadId()
    {
        return $this->container['thread_id'];
    }

    /**
     * Sets thread_id
     *
     * @param string $thread_id thread_id
     *
     * @return $this
     */
    public function setThreadId($thread_id)
    {

        if ((mb_strlen($thread_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $thread_id when calling ConversationUseViewResponse., must be bigger than or equal to 1.');
        }

        $this->container['thread_id'] = $thread_id;

        return $this;
    }

    /**
     * Gets distribution
     *
     * @return string
     */
    public function getDistribution()
    {
        return $this->container['distribution'];
    }

    /**
     * Sets distribution
     *
     * @param string $distribution distribution
     *
     * @return $this
     */
    public function setDistribution($distribution)
    {

        if ((mb_strlen($distribution) < 1)) {
            throw new \InvalidArgumentException('invalid length for $distribution when calling ConversationUseViewResponse., must be bigger than or equal to 1.');
        }

        $this->container['distribution'] = $distribution;

        return $this;
    }

    /**
     * Gets creator_id
     *
     * @return string
     */
    public function getCreatorId()
    {
        return $this->container['creator_id'];
    }

    /**
     * Sets creator_id
     *
     * @param string $creator_id creator_id
     *
     * @return $this
     */
    public function setCreatorId($creator_id)
    {

        if ((mb_strlen($creator_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $creator_id when calling ConversationUseViewResponse., must be bigger than or equal to 1.');
        }

        $this->container['creator_id'] = $creator_id;

        return $this;
    }

    /**
     * Gets org_id
     *
     * @return string
     */
    public function getOrgId()
    {
        return $this->container['org_id'];
    }

    /**
     * Sets org_id
     *
     * @param string $org_id org_id
     *
     * @return $this
     */
    public function setOrgId($org_id)
    {

        if ((mb_strlen($org_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $org_id when calling ConversationUseViewResponse., must be bigger than or equal to 1.');
        }

        $this->container['org_id'] = $org_id;

        return $this;
    }

    /**
     * Gets user_ids
     *
     * @return string[]
     */
    public function getUserIds()
    {
        return $this->container['user_ids'];
    }

    /**
     * Sets user_ids
     *
     * @param string[] $user_ids user_ids
     *
     * @return $this
     */
    public function setUserIds($user_ids)
    {
        $this->container['user_ids'] = $user_ids;

        return $this;
    }

    /**
     * Gets expires
     *
     * @return string
     */
    public function getExpires()
    {
        return $this->container['expires'];
    }

    /**
     * Sets expires
     *
     * @param string $expires expires
     *
     * @return $this
     */
    public function setExpires($expires)
    {

        if ((mb_strlen($expires) < 1)) {
            throw new \InvalidArgumentException('invalid length for $expires when calling ConversationUseViewResponse., must be bigger than or equal to 1.');
        }

        $this->container['expires'] = $expires;

        return $this;
    }

    /**
     * Gets created
     *
     * @return string
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param string $created created
     *
     * @return $this
     */
    public function setCreated($created)
    {

        if ((mb_strlen($created) < 1)) {
            throw new \InvalidArgumentException('invalid length for $created when calling ConversationUseViewResponse., must be bigger than or equal to 1.');
        }

        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets jwt
     *
     * @return string
     */
    public function getJwt()
    {
        return $this->container['jwt'];
    }

    /**
     * Sets jwt
     *
     * @param string $jwt jwt
     *
     * @return $this
     */
    public function setJwt($jwt)
    {

        if ((mb_strlen($jwt) < 1)) {
            throw new \InvalidArgumentException('invalid length for $jwt when calling ConversationUseViewResponse., must be bigger than or equal to 1.');
        }

        $this->container['jwt'] = $jwt;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


