<?php
/**
 * BulkTagmathViewResultsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Forsta Atlas API
 *
 * User and Tag management API for Forsta Messaging Platform
 *
 * OpenAPI spec version: v1
 * Contact: support@forsta.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BulkTagmathViewResultsTest Class Doc Comment
 *
 * @category    Class
 * @description BulkTagmathViewResults
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BulkTagmathViewResultsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BulkTagmathViewResults"
     */
    public function testBulkTagmathViewResults()
    {
    }

    /**
     * Test attribute "userids"
     */
    public function testPropertyUserids()
    {
    }

    /**
     * Test attribute "monitorids"
     */
    public function testPropertyMonitorids()
    {
    }

    /**
     * Test attribute "universal"
     */
    public function testPropertyUniversal()
    {
    }

    /**
     * Test attribute "pretty"
     */
    public function testPropertyPretty()
    {
    }

    /**
     * Test attribute "warnings"
     */
    public function testPropertyWarnings()
    {
    }
}
