<?php
/**
 * UserApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Forsta Atlas API
 *
 * User and Tag management API for Forsta Messaging Platform
 *
 * The version of the OpenAPI document: v1
 * Contact: support@forsta.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UserApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UserApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for userCreate
     *
     * .
     *
     */
    public function testUserCreate()
    {
    }

    /**
     * Test case for userDelete
     *
     * .
     *
     */
    public function testUserDelete()
    {
    }

    /**
     * Test case for userInvite
     *
     * .
     *
     */
    public function testUserInvite()
    {
    }

    /**
     * Test case for userList
     *
     * .
     *
     */
    public function testUserList()
    {
    }

    /**
     * Test case for userPartialUpdate
     *
     * .
     *
     */
    public function testUserPartialUpdate()
    {
    }

    /**
     * Test case for userRead
     *
     * .
     *
     */
    public function testUserRead()
    {
    }

    /**
     * Test case for userUpdate
     *
     * .
     *
     */
    public function testUserUpdate()
    {
    }
}
